---
title: "Vacant Building Intro"
author: "TJ Butler"
format: html
editor: visual
execute:
  cache: true
---

```{r}
#| label: setup
#| include: false

if(!require("pacman")) install.packages("pacman")
pacman::p_load("tidyverse", "sf", "mapview", "gridExtra", "survey", "devtools",
               "ggmosaic", "basemaps", "tidycensus")
```

```{r}
#| label: setup2
#| include: false
vbnCityData <- 
st_read("https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/1/query?outFields=*&where=1%3D1&f=geojson")

csaBoundaries <- 
st_read("https://services1.arcgis.com/UWYHeuuJISiGmgXx/arcgis/rest/services/Community_Statistical_Areas_(CSAs)__Reference_Boundaries_new/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")

load("BAS_data/baltimore-area-survey-2023.Rdata")
load("BAS_data/baltimore-area-survey-2024.Rdata")
load("BAS_data/baltimore-area-survey-2025.Rdata")
```

## Baseplot of VBN's as points

```{r}
#| label: Basemap Practice
#| eval: false

ggplot(vbnCityData) +
  geom_sf()

```


## Mapping VBN's per area
```{r}
#| label: Mapping Per Area

# Want to add in VBN's per 1000 housing units or something like that
# Use tidycensus to get census tract and ACS data to get this number
# Balt City has real property geo info but ACS has already done the work
acsData <- get_acs(geography = "tract", state = "MD", county = "Baltimore city",
                   table = "DP04", year = 2024, geometry = T, survey = "acs1")

acs_data_vacants <- acsData %>% 
  filter(variable %in% c("DP04_0001","DP04_0003")) %>% 
  select(-moe) %>% 
  pivot_wider(names_from = "variable", values_from = "estimate") %>% 
  mutate(vacants_per_1000 = DP04_0003/DP04_0001*1000)
  






ggplot(acs_data_vacants) +
  geom_sf()


plot(acs_data_vacants["vacants_per_1000"])












csaBoundariesIntersected <- csaBoundaries %>%
  mutate(vbns = 
            lengths(st_intersects(csaBoundaries, vbnCityData)),
         vbnsPerArea = vbns / Shape__Area * 1000000)

intersections <-
    lengths(st_intersects(csaBoundaries, vbnCityData))

vbnPerAreaMap <-
  ggplot() +
  geom_sf(data = csaBoundariesIntersected, aes(fill = vbnsPerArea)) +
  scale_fill_viridis_c() +
  theme_minimal() +
  labs(title = "VBN Units per CSA Area",
       fill = "VBNs per sq km")

vbnMap <-
  ggplot() +
  geom_sf(data = csaBoundariesIntersected, aes(fill = vbns)) +
  theme_minimal() +
  labs(title = "VBN Units in Baltimore City",
       fill = "VBN Units")

gridExtra::grid.arrange(vbnMap, vbnPerAreaMap, ncol = 2)
```


## BAS Sentiment Histogram

```{r}
#| label: BAS Sentiment Histogram

# Percentage not frequency of responses
bas24_vac_lot <- bas24 %>%
  count(bas24_nhd_pdvlot) %>% 
  mutate(Percent = round(n / nrow(bas24) * 100, 1))

bas24_vac_bldg <- bas24 %>% 
  count(bas24_nhd_pdvbldg) %>% 
  mutate(Percent = round(n / nrow(bas24) * 100, 1))

bas25_vac_bldg <- bas25 %>% 
  count(bas25_nhd_pbvbld) %>% 
  mutate(Percent = round(n / nrow(bas25) * 100, 1))

vac_lot24 <- ggplot(data = bas24_vac_lot, 
                    mapping = aes(x = bas24_nhd_pdvlot, y = Percent)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS24 Vac Lot") + ylim(c(0,60))

vac_bldg24 <- ggplot(data = bas24_vac_bldg, 
                     mapping = aes(x = bas24_nhd_pdvbldg, 
                                   y = Percent)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS24 Vac Bldg") + ylim(c(0,60))

vac_bldg25 <- ggplot(data = bas25_vac_bldg, 
                     mapping = aes(x = bas25_nhd_pbvbld, y = Percent)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS25 Vac Bldg") + ylim(c(0,60))

gridExtra::grid.arrange(vac_lot24, vac_bldg24, vac_bldg25, ncol = 3)
```


## Distribution of VBN's per XX stratified by Vacant Building Sentiment Response: 24 25
```{r}
#| label: VBN by vacant building sentiment cross-tab

```




## Demographic Cross Tabs

```{r}
#| label: Demographic cross tab

vac_lot_race24 <- ggplot(data = bas24, mapping = aes(x = bas24_nhd_pdvlot)) + 
  geom_bar() + theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS 24 Vac Lot Sentiment") + facet_wrap(~bas24_dem_raceeth4)

vac_lot_race24

vac_bldg_race24 <- ggplot(data = bas24, mapping = aes(x = bas24_nhd_pdvbldg)) + 
  geom_bar() + theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS 24 Vac Bldg Sentiment") + facet_wrap(~bas24_dem_raceeth4)

vac_bldg_race25 <- ggplot(data = bas25, mapping = aes(x = bas25_nhd_pbvbld)) + 
  geom_bar() + theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS 25 Vac Bldg Sentiment") + facet_wrap(~bas25_dem_raceeth4)

vac_bldg_race25

vac_lot_sex24 <- ggplot(data = bas24, mapping = aes(x = bas24_nhd_pdvlot)) + 
  geom_bar() + theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS 24 Vac Lot Sentiment") + facet_wrap(~bas24_dem_gender)
  

vac_bldg_sex24 <- ggplot(data = bas24, mapping = aes(x = bas24_nhd_pdvbldg)) + 
  geom_bar() + theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS 24 Vac Bldg Sentiment") + facet_wrap(~bas24_dem_gender)

vac_bldg_sex25 <- ggplot(data = bas25, mapping = aes(x = bas25_nhd_pbvbld)) + 
  geom_bar() + theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  labs(x="BAS 25 Vac Bldg Sentiment") + facet_wrap(~bas25_dem_gender)
```


## Association Between Vacant Buildings and other Neighborhood Indicators
```{r}
#| label: VBN and Other Neighborhood Indicators

bas24_vac_blg_vs_walksafe <- bas24 %>% 
  select(bas24_nhd_pdvbldg, bas24_nhd_walksafe) %>% 
  group_by(bas24_nhd_pdvbldg) %>% 
  count(bas24_nhd_walksafe)

# Grouped bar plot
ggplot(data = bas24_vac_blg_vs_walksafe, 
       aes(x = bas24_nhd_pdvbldg, y = n, fill = bas24_nhd_walksafe)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  ylab("Frequency") + xlab("Vacant Building Sentiment") + 
  theme(axis.text.x = element_text(angle = 30, vjust = 0.8)) + 
  ggtitle("Bar chart of safe walking sentiment by vacant building sentiment")

# Mosaic plot - relative frequencies by vacant building sentiment
ggplot(data = bas24) +
  ggmosaic::geom_mosaic(aes(x = product(bas24_nhd_pdvbldg), 
                            fill = bas24_nhd_walksafe)) + 
  theme(axis.text.x = element_text(angle = 30, vjust = 0.8))
```